name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run build.py
        run: | 
          cd $GITHUB_WORKSPACE
          python3 -m pip install -r requirements.txt
          python3 build.py
      - name: Setup deploy branch
        run: |
          mv .git output/
          cd output
          git init .
          git config user.email "areebbeigh@users.noreply.github.com"
          git config --global user.name "areebbeigh"
          git add -A
          git stash
          git fetch
          git checkout deploy
          git stash apply
          git commit -m 'Deploy'
          git push origin deploy -f
